C_FILES = src/cfiles/str/ft_striteri.c \
src/cfiles/str/ft_isstrfloat.c \
src/cfiles/str/ft_strstr.c \
src/cfiles/str/ft_isstrint.c \
src/cfiles/str/ft_strncat.c \
src/cfiles/str/ft_strtrim.c \
src/cfiles/str/ft_strsplit.c \
src/cfiles/str/ft_strdel.c \
src/cfiles/str/ft_strndup.c \
src/cfiles/str/ft_strnstr.c \
src/cfiles/str/ft_strsub.c \
src/cfiles/str/ft_strrchr.c \
src/cfiles/str/ft_strmapi.c \
src/cfiles/str/ft_strjoin.c \
src/cfiles/str/ft_strmap.c \
src/cfiles/str/ft_strclr.c \
src/cfiles/str/ft_strtrimfree.c \
src/cfiles/str/ft_striter.c \
src/cfiles/str/ft_strncpy.c \
src/cfiles/str/ft_move_word.c \
src/cfiles/str/ft_strtabfree.c \
src/cfiles/str/ft_strsplitcount.c \
src/cfiles/str/ft_strlcat.c \
src/cfiles/str/ft_charcat.c \
src/cfiles/strconv/ft_atoll.c \
src/cfiles/strconv/ft_atoi.c \
src/cfiles/strconv/ft_itoa.c \
src/cfiles/strconv/ft_atof.c \
src/cfiles/strconv/ft_atol.c \
src/cfiles/sort/ft_isort.c \
src/cfiles/sort/ft_nlist_sort.c \
src/cfiles/sort/sort_int.c \
src/cfiles/sort/ft_lstsort.c \
src/cfiles/sort/sort_str.c \
src/cfiles/sort/ft_qsort.c \
src/cfiles/list/ft_lstlast.c \
src/cfiles/list/ft_nlist_merge.c \
src/cfiles/list/ft_nlist_init.c \
src/cfiles/list/ft_nlist_create.c \
src/cfiles/list/ft_nlist_add.c \
src/cfiles/list/ft_lstadd.c \
src/cfiles/list/ft_lstiter.c \
src/cfiles/list/ft_lstnew_raw.c \
src/cfiles/list/ft_lstdelone.c \
src/cfiles/list/ft_dlstdelone.c \
src/cfiles/list/ft_nlist_delete.c \
src/cfiles/list/ft_dlstdestroy.c \
src/cfiles/list/ft_lstmap.c \
src/cfiles/list/ft_nlist_addback.c \
src/cfiles/list/ft_nlist_reverse.c \
src/cfiles/list/ft_nlist_iter.c \
src/cfiles/list/ft_nlist_addfront.c \
src/cfiles/list/ft_lstreverse.c \
src/cfiles/list/ft_lstnew.c \
src/cfiles/list/ft_lstdel.c \
src/cfiles/list/ft_nlist_delone.c \
src/cfiles/list/ft_dlstaddfront.c \
src/cfiles/list/ft_dlstclear.c \
src/cfiles/list/ft_nlist_rem.c \
src/cfiles/list/ft_dlstaddback.c \
src/cfiles/list/ft_dlstnew.c \
src/cfiles/list/ft_lstadd_back.c \
src/cfiles/list/ft_dlstinit.c \
src/cfiles/list/ft_lstbefore.c \
src/cfiles/list/ft_nlist_destroy.c \
src/cfiles/gnl/get_next_line.c \
src/cfiles/fmt/ft_printf_string.c \
src/cfiles/fmt/ft_printf_utilities.c \
src/cfiles/fmt/ft_printf_nbparse.c \
src/cfiles/fmt/ft_printf_precision.c \
src/cfiles/fmt/ft_printf_nb.c \
src/cfiles/fmt/ft_printf_wchar.c \
src/cfiles/fmt/ft_printf_padding.c \
src/cfiles/fmt/ft_printf_utilities_2.c \
src/cfiles/fmt/ft_printf_string_2.c \
src/cfiles/fmt/ft_printf.c \
src/cfiles/fmt/ft_printf_itobase.c \
src/cfiles/fmt/ft_printf_wstring.c \
src/cfiles/fmt/ft_printf_lltoa.c \
src/cfiles/fmt/ft_printf_getflag3.c \
src/cfiles/fmt/ft_printf_nb_2.c \
src/cfiles/io/ft_failure.c \
src/cfiles/io/ft_putstr_fd.c \
src/cfiles/io/ft_putnbr.c \
src/cfiles/io/ft_putnbr_fd.c \
src/cfiles/io/ft_putstr.c \
src/cfiles/io/ft_putchar.c \
src/cfiles/io/ft_error.c \
src/cfiles/io/ft_putchar_fd.c \
src/cfiles/io/ft_putendl_fd.c \
src/cfiles/io/ft_putulong.c \
src/cfiles/io/ft_hexdump.c \
src/cfiles/io/ft_putendl.c \
src/cfiles/mem/ft_memswap.c \
src/cfiles/mem/ft_realloc.c \
src/cfiles/mem/ft_memmove.c \
src/cfiles/mem/ft_memccpy.c \
src/cfiles/mem/ft_memalloc.c \
src/cfiles/mem/ft_memdel.c \

C_DIRS = src/cfiles/fmt \
src/cfiles/gnl \
src/cfiles/io \
src/cfiles/list \
src/cfiles/mem \
src/cfiles/sort \
src/cfiles/str \
src/cfiles/strconv \

S_FILES = src/sfiles/ft_ctypes/ft_isascii.s \
src/sfiles/ft_ctypes/ft_isalpha.s \
src/sfiles/ft_ctypes/ft_isprint.s \
src/sfiles/ft_ctypes/ft_isdigit.s \
src/sfiles/ft_ctypes/ft_isalnum.s \
src/sfiles/ft_ctypes/ft_isspace.s \
src/sfiles/strings/ft_strcat.s \
src/sfiles/strings/ft_tolower.s \
src/sfiles/strings/ft_strequ.s \
src/sfiles/strings/ft_strnew.s \
src/sfiles/strings/ft_strnequ.s \
src/sfiles/strings/ft_strlen.s \
src/sfiles/strings/ft_toupper.s \
src/sfiles/strings/ft_strcmp.s \
src/sfiles/strings/ft_strcpy.s \
src/sfiles/strings/ft_strchr.s \
src/sfiles/strings/ft_strdup.s \
src/sfiles/strings/ft_strncmp.s \
src/sfiles/io/ft_puts.s \
src/sfiles/io/ft_cat.s \
src/sfiles/mem/ft_memcmp.s \
src/sfiles/mem/ft_memset.s \
src/sfiles/mem/ft_memcpy.s \
src/sfiles/mem/ft_bzero.s \
src/sfiles/mem/ft_memchr.s \

S_DIRS = src/sfiles/ft_ctypes \
src/sfiles/io \
src/sfiles/mem \
src/sfiles/strings \

L_FILES = legacy/ft_toupper.c \
legacy/ft_strcpy.c \
legacy/ft_isdigit.c \
legacy/ft_strncmp.c \
legacy/ft_strchr.c \
legacy/ft_isalpha.c \
legacy/ft_isspace.c \
legacy/ft_strnew.c \
legacy/ft_isalnum.c \
legacy/ft_strequ.c \
legacy/ft_isascii.c \
legacy/ft_strlen.c \
legacy/ft_memchr.c \
legacy/ft_memcpy.c \
legacy/ft_strcat.c \
legacy/ft_strnequ.c \
legacy/ft_memset.c \
legacy/ft_strcmp.c \
legacy/ft_memcmp.c \
legacy/ft_bzero.c \
legacy/ft_isprint.c \
legacy/ft_puts.c \
legacy/ft_strdup.c \
legacy/ft_tolower.c \
